### PR TITLE
Fix for issue #15

### PR DESCRIPTION
**Pull request by Stephan202**
You were right that resolution of #4 made resolution of #15 very easy.

One question: what about testing? We can either:
1. Decide that a code review and manual testing using the POM in #15 is good enough.
2. Create an IT with the example POM and prevent the original issue from being merely logged, but have it bubble up as a fatal exception instead. (E.g. by changing the `IllegalStateException` at `AbstractReduntantVersionRule:135` to an `AssertionError`.)
3. Create an IT with the example POM and verify that no warning is logged anymore. This is probably more trouble than it's worth. (Never done this with log4j directly. If you were to use SLF4J, I'd use [slf4j-test](http://projects.lidalia.org.uk/slf4j-test/).)

Let me know what you think :)

### CODE REVIEW

**Comment by lewisd32** [comment]
I'm glad #4 did help with this.
Good question about testing.  The fix itself looks good, thanks for doing that.  I would like to have some automated testing around it though.
I agree that 3 is probably more trouble than it's worth.  I wouldn't mind switching the project over to SLF4J at some point, but doing all that just to test this fix is seems a bit overkill.
I'm reluctant to make these exceptions fatal, since that would mean bugs in this plugin would halt and fail people's maven builds. I'd prefer to let people still be able to get some value from the plugin, even if their POMs do expose bugs in it.
I think this can be tested in an IT, in a similar way to how the existing ITs work.  They invoke `verify.bsh`, which reads the `build.log` output and asserts that it sees the expected things logged, or not logged.  The test for this could use the example pom, and ensure that no warnings are logged.  Take a look at `src\it\it-pass-when-no-rules-configured` for an example that I think would be a good starting point.

**Comment by lewisd32** [comment]
Thinking about this inspired me to do some work to improve the integration testing.  I've added validation that all integration tests complete without any warnings being logged by the code.  I would recommend rebasing your branch onto the latest master, to get the changes to the integration tests.
At that point, if you add an IT using the example pom from #15 following the example of `src\it\it-pass-when-no-rules-configured`, it should ensure that your fix does indeed stop warnings from being logged.

**Comment by Stephan202** [comment]
Thanks, that was very helpful. I have now:

1. Rebased the branch.
2. Added an integration test.
3. Squashed the commits and expanded the commit message.

I verified the validity of the IT by running it on master and on the branch. It fails in the first case and passed in the second, as expected.

**Comment by lewisd32** [comment]
Wonderful.  That test looks great.  I was about to merge this, because it looks great, but I had a thought that this *may* introduce a new bug.  I haven't investigated yet though.

For some artifact, if one of the redundant dependencies had `<type>jar</type>` on it, and the other had no type, before this fix, `resolveObject` would have found it.  With this fix, the `and not(type)` would prevent it from finding it, I think?
If that is actually a new bug, then maybe something like `and (not(type) or type='jar')` would fix it?  (Assuming JXPath can handle a query like that)

**Comment by Stephan202** [comment]
Thanks!

**Pull request merged**
